# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ATCodeChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ATCodeChallenge
	pod 'Alamofire'
	pod 'AlamofireObjectMapper'
	
  target 'ATCodeChallengeTests' do
    inherit! :search_paths
  end

end
